version: '2'

#
# symlink `ln -s docker-compose.override-dev-example.yaml  docker-compose.override.yaml`
# to override settings for development
#

services:

  # override frontend with dev configuration
  frontend:
    build:
      dockerfile: Dockerfile-dev

    environment:
      NODE_ENV: development

    ports:
        - 3000:3000
        - 3001:3001

    command: bash -c "cd code; npm run docker-dev"
    tty: true